FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /opt/lllars

COPY . .

RUN apt-get update
RUN apt-get install -y --no-install-recommends bash
RUN rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir .
RUN chmod +x /opt/lllars/docker/runtime-entrypoint.sh

ENTRYPOINT ["/opt/lllars/docker/runtime-entrypoint.sh"]
